config/routes.rb
Clicker::Application.routes.draw do

   root :to => "problem_sets#login"

  resources :problem_sets do
    resources :questions do
      resources :responses
    end
  end

  match "problem_sets/:id/result/" => "problem_sets#result"
  match "login/" => "problem_sets#login"
  match "logout/" => "problem_sets#logout"
end

app/models/problem_set.rb
class ProblemSet < ActiveRecord::Base
  has_many :questions
end

app/controllers/problem_sets_controller.rb
class ProblemSetsController < ApplicationController
  # GET /problem_sets
  # GET /problem_sets.xml
  def index
    @problem_sets = ProblemSet.all
    @problem_set = ProblemSet.new
    if session[:user_id].nil?
        session[:redirect_url] = problem_sets_url
        redirect_to :action => "login"
    else 
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @problem_sets }
      end
    end
  end

  # GET /problem_sets/1
  # GET /problem_sets/1.xml
  def show
    @problem_set = ProblemSet.find(params[:id])
    if session[:user_id].nil?
        session[:redirect_url] = problem_set_path(@problem_set)
        redirect_to :action => "login"
    else 
      @questions = Question.where(:problem_set_id => @problem_set.id)
      @question = Question.where(:problem_set_id => @problem_set.id).first

      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @problem_set }
      end
    end
  end

  # GET /problem_sets/new
  # GET /problem_sets/new.xml
  def new
    @problem_set = ProblemSet.new
    if session[:user_id].nil?
      session[:redirect_url] = "/problem_sets/new/"
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to :action => "index"
      else
        respond_to do |format|
          format.html # new.html.erb
          format.xml  { render :xml => @problem_set }
        end
      end
    end
  end

  # GET /problem_sets/1/edit
  def edit
    @problem_set = ProblemSet.find(params[:id])
    if session[:user_id].nil?
      session[:redirect_url] = "/problem_sets/#{@problem_set.id}/questions/edit/"
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to :action => "index"
      end
    end
  end

  # POST /problem_sets
  # POST /problem_sets.xml
  def create
    @problem_set = ProblemSet.new(params[:problem_set])
    if params[:user_id]
      session[:user_id] = params[:user_id]
      if session[:redirect_url].nil?
        redirect_to :action => "index"
      else
        r_to = session[:redirect_url]
        session[:redirect_url] = nil
        redirect_to(r_to) 
      end
    else
      respond_to do |format|
        if @problem_set.save
          format.html { redirect_to(@problem_set, :notice => 'Problem set was successfully created.') }
          format.xml  { render :xml => @problem_set, :status => :created, :location => @problem_set }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @problem_set.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /problem_sets/1
  # PUT /problem_sets/1.xml
  def update
    @problem_set = ProblemSet.find(params[:id])

    respond_to do |format|
      if @problem_set.update_attributes(params[:problem_set])
        format.html { redirect_to(@problem_set, :notice => 'Problem set was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @problem_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /problem_sets/1
  # DELETE /problem_sets/1.xml
  def destroy
    @problem_set = ProblemSet.find(params[:id])
    @problem_set.destroy

    respond_to do |format|
      format.html { redirect_to(problem_sets_url) }
      format.xml  { head :ok }
    end
  end

  #TODO: to be moved when a user model is implemented
  def login
    @problem_set = ProblemSet.new
    @question = Question.new
    @response = Response.new
    
    render :action => "login"
  end
  def logout
    session[:user_id] = nil
    redirect_to :action => "login"
  end

  def result
    @problem_set = ProblemSet.find(params[:id])
   if session[:user_id].nil?
       session[:redirect_url] = "/problem_sets/#{@problem_set.id}/result/"
        redirect_to :action => "login"
   else 

    questions   = Question.where(:problem_set_id => @problem_set.id).all
    @result = []
    questions.each_with_index do |q, i| 
      @result[i] = {}
      @result[i][:question] = q
      @result[i][:answers] = Answer.where(:question_id => q.id)
      total = {}
      res = Response.where(:question_id => q.id)
      @result[i][:answers].each_with_index do |a, j|
        total[j] = res.where(:answer_id => a.id).size
      end
      @result[i][:total] = total
      @result[i][:response] = Response.where(:user_id => session[:user_id], :question_id => q.id).first
    end

    #user_id hardcoded, TODO:// create user model 
    if @result[0][:response].nil? && session[:user_id] != '126126126126126'
      respond_to do |format|
         format.html { redirect_to(problem_set_questions_path(@problem_set.id), :notice => "Must take the quiz first to see the results!!!") }
      end
    else
      render :action => "result" 
    end
   end
  end










end

app/helpers/problem_sets_helper.rb
module ProblemSetsHelper
end

app/views/problem_sets/_foot.html.erb
<% if session[:user_id].to_i == 126126126126126 %>
  <%= link_to 'New Problem Set', new_problem_set_path %> 
  <% if @problem_set.id %>
    | <%= link_to 'Edit Problem Set', edit_problem_set_path(@problem_set) %> |
  <% end %>
<% end %>

<% if @problem_set %>
  <%= link_to 'Back to Probelm Set Listing', problem_sets_path %>
<% end %>

app/views/problem_sets/_form.html.erb
<%= form_for(@problem_set) do |f| %>
  <% if @problem_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_set.errors.count, "error") %> prohibited this problem_set from being saved:</h2>

      <ul>
      <% @problem_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br />
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/problem_sets/_login_form.html.erb
<%= form_for(@problem_set) do |f| %>
  <% if @problem_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@problem_set.errors.count, "error") %> prohibited this problem_set from being saved:</h2>

      <ul>
      <% @problem_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <h2>Please enter User ID before you begin</h2>
  <div class="fields">
    <label>User ID #:</label>
    <input id="user_id" name="user_id" size="30" type="text" value="">
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "ENTER"%>
  </div>
<% end %>

app/views/problem_sets/edit.html.erb
<h1>Editing problem_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @problem_set %> |
<%= render "foot" %>

app/views/problem_sets/index.html.erb
<% if session[:user_id] %>
<h1>Listing of all Problem Sets</h1>


<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @problem_sets.each do |problem_set| %>
  <tr>
    <td><%= problem_set.title %></td>
    <td><%= link_to 'Take Quiz', problem_set_questions_path(problem_set) %></td>
    <td><%= link_to 'About', problem_set %></td>
    <% if session[:user_id].to_i == 126126126126126 %>
      <td><%= link_to 'Edit', edit_problem_set_path(problem_set) %></td>
      <td><%= link_to 'Destroy', problem_set, :confirm => 'Are you sure?', :method => :delete %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= render "foot" %>
<% else %>
 <%= render 'login_form' %>
<% end %>

app/views/problem_sets/login.html.erb
<%= render "login_form" %>

app/views/problem_sets/login_form.html.erb
<%= form_for([@problem_set, @question, @response]) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <input id="user_id" name="user_id" size="30" value="" type="text" />
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

app/views/problem_sets/new.html.erb
<h1>Create a new Problem Set</h1>

<%= render 'form' %>

<%= render "foot" %>

app/views/problem_sets/result.html.erb
<h1>Problem Set#<%= @problem_set.id %> "<%= @problem_set.title %>" Results</h1>
<h3>for User #<%= session[:user_id] %></h3>

<% @result.each  do |r| %>

  <strong>Question #<%= r[:question].count%></strong>
  <ol type = 'a'>
  <% r[:answers].each_with_index do |res, i| %>
    <li><%= res.answer %> 
        <% if not r[:response].nil? %>
         <% if res.correct %>
                <% if r[:response].answer_id == res.id %>
                  Correct!
                <% else %>
                  <--Correct Answer
                <% end %>
              <% else %>
                <% if r[:response].answer_id == res.id %>
                  <-- Your Choice
                <% end %>
              <% end %>
        <% end %>
    </li> Choosen <%= r[:total][i] %> time(s) total.<br/>
  <% end %>
  </ol>
<br/>
<% end %>

<%= render "foot" %>

app/views/problem_sets/show.html.erb
<p id="notice"><%= notice %></p>


  <h2>Title: <%= @problem_set.title %></h2>


<p>
  <strong>Summary:</strong><br/>
  <em><%= @problem_set.summary %></em>
</p>

  <%= link_to 'The Questions', problem_set_questions_path(@problem_set) %> 

<br/><br/>

<%= render "foot" %>