config/routes.rb
Clicker::Application.routes.draw do

   root :to => "problem_sets#login"

  resources :problem_sets do
    resources :questions do
      resources :responses
    end
  end

  match "problem_sets/:id/result/" => "problem_sets#result"
  match "login/" => "problem_sets#login"
  match "logout/" => "problem_sets#logout"
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  # GET /responses
  # GET /responses.xml
  def index
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.where(:problem_set_id => @problem_set.id, :count => params[:question_id].to_i).first
    if session[:user_id].nil?
      session[:redirect_url] = "/problem_sets/#{@problem_set.id}/questions/#{@question.count}/responses/"
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to("/problem_sets/#{@problem_set.id}/questions/#{@question.count}/")
      else
        @responses = Response.where(:question_id => @question.id)

        respond_to do |format|
         format.html # index.html.erb
         format.xml  { render :xml => @responses }
        end
      end
    end
  end

  # GET /responses/1
  # GET /responses/1.xml
  def show
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.where(:problem_set_id => @problem_set.id, :count=> params[:question_id].to_i).first
    @response = Response.find(params[:id])
    if session[:user_id].nil?
      session[:redirect_url] = "/problem_sets/#{@problem_set.id}/questions/#{@question.count}/responses/#{@response.id}"
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to :action => "index" 
      else
        @answer = Answer.find(@response.answer_id)

        respond_to do |format|
          format.html # show.html.erb
          format.xml  { render :xml => @response }
        end
      end
    end
  end

  # GET /responses/new
  # GET /responses/new.xml
  def new
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.where(:problem_set_id => params[:problem_set_id])[params[:question_id].to_i - 1]
    if session[:user_id].nil?
      session[:redirect_url] = "/problem_sets/#{@problem_set.id}/questions/#{@question.count}/responses/new/"
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to :action => "index" 
      else
        @response = Response.new
        @answer = Answer.where(:question_id => @question.id)
      
       respond_to do |format|
         format.html # new.html.erb
         format.xml  { render :xml => @response }
       end
     end
    end
  end

  # GET /responses/1/edit
  def edit
    @response = Response.find(params[:id])
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.find(params[:question_id])
    if session[:user_id].nil?
      session[:redirect_url] = edit_problem_set_question_response_path(@problem_set.id, @question.count, @response)
      redirect_to("/login/")
    else
      if session[:user_id].to_i != 126126126126126
        flash[:notice] = "NO PERMISSION!"
        redirect_to :action => "index" 
      else
        @answer = Answer.where(:id => @response.answer_id).all
      end
    end
  end

  # POST /responses
  # POST /responses.xml
  def create
    if not session[:user_id]
      session[:user_id] = params[:user_id]
      redirect_to(problem_set_question_path(session[:prob_id], session[:ques_id])) 
    else
      @problem_set = ProblemSet.find(params[:problem_set_id])  
      @question = Question.find(params[:question_id])
      @answer = Answer.find(params[:response])
      @response = Response.new( :answer_id => @answer.id, :result => @answer.correct, :question_id => @question.id, :problem_set_id => @problem_set.id, :user_id => session[:user_id])    
    
      if @problem_set.question_count > @question.count
        next_question = Question.where(:problem_set_id => @problem_set.id, :count => @question.count + 1).first
        result = problem_set_question_path(@problem_set.id, next_question.count)
      else
        result = "/problem_sets/#{@problem_set.id}/result/"
      end
      respond_to do |format|
        if @response.save
          format.html { redirect_to(result, :notice => 'Response was successfully created.') }
          format.xml  { render :xml => @response, :status => :created, :location => @response }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /responses/1
  # PUT /responses/1.xml
  def update
    @response = Response.find(params[:id])
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.find(params[:question_id])

    respond_to do |format|
      if @response.update_attributes(params[:response])
        format.html { redirect_to(@response, :notice => 'Response was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @response.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /responses/1
  # DELETE /responses/1.xml
  def destroy
    @problem_set = ProblemSet.find(params[:problem_set_id])
    @question = Question.find(params[:question_id])
    @response = Response.find(params[:id])
    @response.destroy

    respond_to do |format|
      format.html { redirect_to(problem_set_question_responses_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for([@problem_set, @question, @response]) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% @answer.each_with_index do |a, i| %>
  <div class="fields">
    <input id="answer_<%= i %>" name="response" size="30" type="radio" value="<%= a.id %>"> <%= a.answer %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

app/views/responses/_login_form.html.erb
<%= form_for([@problem_set, @question, @response]) do |f| %>
  <% if @response.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@response.errors.count, "error") %> prohibited this response from being saved:</h2>

      <ul>
      <% @response.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <input id="user_id" name="user_id" size="30" value="" type="text" />
  </div>
  <br />
  <div class="actions">
    <%= f.submit "Submit Answer" %>
  </div>
<% end %>

app/views/responses/edit.html.erb
<h1>Editing response</h1>

<%= render 'form' %>

    <%= link_to 'Show', problem_set_question_response_path(@problem_set.id, @question.id, response.id) %> |
    <%= link_to 'Back', problem_set_question_responses_path %>

app/views/responses/index.html.erb
<h1>Listing responses</h1>

<table>
  <tr>
    <th>User ID</th>
    <th>Answer ID</th>
    <th>Question ID</th>
  </tr>

<% @responses.each do |response| %>
  <tr>
    <td><%= response.user_id %></td>
    <td><%= response.answer_id %></td>
    <td><%= response.question_id %></td>
    <td><%= link_to 'Show', problem_set_question_response_path(@problem_set.id, params[:question_id], response.id) %></td>
    <td><%= link_to 'Edit', edit_problem_set_question_response_path(@problem_set.id, @question.id, response) %></td>
    <td><%= link_to 'Destroy', [@problem_set, @question, response], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Response', new_problem_set_question_response_path %>

app/views/responses/new.html.erb
<h1> Problem Set <%= @problem_set.id %> </h1>
<h2>Question #<%= params[:question_id]%>: <%= @question.problem %></h2>

<%= render 'form' %>

<%= link_to 'Back', problem_set_question_responses_path %>

app/views/responses/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Problem Set #<%= params[:problem_set_id] %>
<h2>Question #<%= params[:question_id] %>: <%= @question.problem %></h2>

<% if @response.result %>
  Correct!
<% else %>
  WRONG!
<% end %>
<%= @answer.answer %>
<br />
<%= link_to 'Back', problem_set_question_responses_path %>